name: create-release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true

jobs:
  release:
    uses: ckotzbauer/actions-toolkit/.github/workflows/toolkit-release-nodejs.yml@0.6.0
    with:
      node-version: 16
      version: ${{ github.event.inputs.version }}
      build-commands: |
        npm ci
        npm run package
        npm test
      artifact-path: dist/
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      pat: ${{ secrets.REPO_ACCESS }}

  update-tag:
    needs: [release]
    runs-on: ubuntu-latest
    steps:
      - name: Update v1 tag
        run: |
          git tag -fa v1 -m "Update v1 tag"
          git push origin v1 --force
